'use client';
import {useEffect,useMemo,useRef,useState,Suspense,memo} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Environment,Lightformer,MeshReflectorMaterial,useTexture} from '@react-three/drei';
import {EffectComposer,SMAA} from '@react-three/postprocessing';
import * as THREE from 'three';
import {RectAreaLightUniformsLib} from 'three/addons/lights/RectAreaLightUniformsLib.js';
RectAreaLightUniformsLib.init();
import {artworks,walls,sampleRoute,duration,destinations,collisionAt} from '../lib/route.mjs';
import {artTexture,artSurface,artLabel} from './textures';
const exhibitionOrder=artworks.map((_,i)=>i).sort((a,b)=>destinations[a]-destinations[b]);
type State={time:number;playing:boolean;speed:number;ready:boolean;fps:number;frames:number;complete:boolean;phase:string;artwork:number;collisions:string[];error:string};
const initial:State={time:0,playing:true,speed:1,ready:false,fps:0,frames:0,complete:false,phase:'Arrival',artwork:-1,collisions:[],error:''};
function Box({position,size,material,...rest}:{position:number[];size:number[];material?:THREE.Material;[key:string]:any}){return <mesh position={position as [number,number,number]} material={material} castShadow receiveShadow {...rest}><boxGeometry args={size as [number,number,number]}/>{!material&&<meshStandardMaterial color="#e8e7e1" roughness={.8}/>}</mesh>;}
function contactMap(){const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d')!;const image=ctx.createImageData(256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const edge=Math.min(x,255-x,y,255-y)/256;const a=Math.min(1,edge/.12);const i=(y*256+x)*4;image.data[i]=image.data[i+1]=image.data[i+2]=35;image.data[i+3]=Math.round(a*a*255);}ctx.putImageData(image,0,0);return new THREE.CanvasTexture(c);}
function Artwork({index}:{index:number}){const a=artworks[index];const texture=useMemo(()=>artTexture(index),[index]);const relief=useMemo(()=>artSurface(index),[index]);const label=useMemo(()=>artLabel(a.title,a.medium,a.year),[a.title,a.medium,a.year]);const contact=useMemo(()=>contactMap(),[]);return <group position={a.position as [number,number,number]} rotation={a.rotation as [number,number,number]}>
 <mesh position={[0,-.013,-.105]}><planeGeometry args={[a.size[0]+.21,a.size[1]+.21]}/><meshBasicMaterial map={contact} transparent opacity={.22} depthWrite={false}/></mesh>
 <Box position={[0,0,-.04]} size={[a.size[0]+.035,a.size[1]+.035,.08]} material={new THREE.MeshStandardMaterial({color:"#8b816e",roughness:.78})}/>
 <mesh position={[0,0,.008]} castShadow receiveShadow><boxGeometry args={[a.size[0],a.size[1],.045]}/><meshStandardMaterial map={texture} normalMap={relief.normalMap} roughnessMap={relief.roughnessMap} normalScale={new THREE.Vector2(.18,.18)} roughness={.84} metalness={0}/></mesh>
 <mesh position={[a.size[0]/2+.23,-a.size[1]/2+.1,-.065]}><planeGeometry args={[.24,.105]}/><meshStandardMaterial map={label} color="#f2f0e9" roughness={.92}/></mesh>
 </group>;}
function WallLettering(){const texture=useMemo(()=>{const c=document.createElement('canvas');c.width=1024;c.height=512;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,1024,512);ctx.fillStyle='#34352f';ctx.textAlign='center';ctx.font='95px Arial';ctx.fillText('VÆST',512,210);ctx.font='19px Arial';ctx.fillText('SPACE BETWEEN / 2026',512,310);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;},[]);return <mesh position={[-3.65,2.22,4.87]} rotation={[0,Math.PI,0]}><planeGeometry args={[2,.95]}/><meshStandardMaterial map={texture} transparent depthWrite={false} roughness={1}/></mesh>;}
function useLocalSurface(kind:'plaster'|'concrete'){const textures=useTexture(['/textures/'+kind+'-diffuse.jpg','/textures/'+kind+'-roughness.jpg','/textures/'+kind+'-normal.jpg']);return useMemo(()=>{const maps=textures.map((t,i)=>{let map=t.clone();if(i===0){const image=t.image as HTMLImageElement;const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d')!;context.drawImage(image,0,0);const data=context.getImageData(0,0,canvas.width,canvas.height);for(let j=0;j<data.data.length;j+=4){const neutral=.2126*data.data[j]+.7152*data.data[j+1]+.0722*data.data[j+2];for(let channel=0;channel<3;channel++)data.data[j+channel]=kind==='concrete'?118+(neutral-53)*.38:242+(data.data[j+channel]-150)*.02;}context.putImageData(data,0,0);map=new THREE.CanvasTexture(canvas);}map.wrapS=map.wrapT=THREE.RepeatWrapping;map.repeat.set(kind==='concrete'?5:4,kind==='concrete'?6.5:4);map.colorSpace=i===0?THREE.SRGBColorSpace:THREE.NoColorSpace;map.anisotropy=16;map.needsUpdate=true;return map;});return {map:maps[0],roughnessMap:maps[1],normalMap:maps[2]};},[textures[0],textures[1],textures[2],kind]);}
function GalleryWall({wall,plaster}:{wall:typeof walls[number];plaster:THREE.MeshStandardMaterial}){const geometry=useMemo(()=>new THREE.BoxGeometry(...wall.min.map((v,i)=>wall.max[i]-v) as [number,number,number]),[wall]);return <mesh position={wall.min.map((v,i)=>(v+wall.max[i])/2) as [number,number,number]} geometry={geometry} material={plaster}/>;}
function GalleryCeiling(){const white=useMemo(()=>new THREE.MeshStandardMaterial({color:'#ffffff',roughness:.94,emissive:'#ffffff',emissiveIntensity:.65}),[]);const bands=[[-4.445,1.51],[0,1.82],[4.445,1.51]];const crossBands=[[-4.57,1.26],[-1.5,1.12],[1.5,1.12],[4.75,1.62],[7.82,.76]];return <>
 {bands.map(([x,width])=><Box key={'long'+x} position={[x,4.08,1.5]} size={[width,.16,13.4]} material={white}/>)}
 {[-2.3,2.3].flatMap(x=>crossBands.map(([z,depth])=><Box key={x+','+z} position={[x,4.08,z]} size={[2.78,.16,depth]} material={white}/>))}
 {[-2.3,2.3].flatMap(x=>[-3,0,3,6.5].map(z=><group key={'rooflight'+x+','+z}>
  {[-1,1].map(side=><Box key={'edgeX'+side} position={[x+side*1.382,4.035,z]} size={[.016,.07,1.88]} material={white}/>)}
  {[-1,1].map(side=><Box key={'edgeZ'+side} position={[x,4.035,z+side*.932]} size={[2.78,.07,.016]} material={white}/>)}
  <mesh rotation={[Math.PI/2,0,0]} position={[x,4.062,z]}><planeGeometry args={[2.748,1.848]}/><meshStandardMaterial color="#fff" emissive="#f6faff" emissiveIntensity={2.7} roughness={1}/></mesh>
  <rectAreaLight position={[x,4.05,z]} rotation={[-Math.PI/2,0,0]} width={2.748} height={1.848} intensity={1.65} color="#fafcff"/>
 </group>))}

 </>;}
function SpaceScene({quality}:{quality:boolean}){const plasterMaps=useLocalSurface('plaster');const plaster=useMemo(()=>new THREE.MeshStandardMaterial({...plasterMaps,color:'#ffffff',roughness:.9,normalScale:new THREE.Vector2(.008,.008),emissive:'#ffffff',emissiveIntensity:.16}),[plasterMaps]);const floor=useLocalSurface('concrete');const floorGeometry=useMemo(()=>{const g=new THREE.PlaneGeometry(10.4,13.4);g.setAttribute('uv1',g.getAttribute('uv').clone());return g;},[]);return <>
 <color attach="background" args={['#d6d4cc']}/><fog attach="fog" args={['#e4e3dc',15,38]}/>
 <hemisphereLight args={['#ffffff','#e8e9e6',.55]}/><ambientLight intensity={.1}/>
 <Environment resolution={256} frames={1}>
  <Lightformer form="rect" intensity={2.1} color="#ffffff" position={[0,3.9,0]} rotation={[Math.PI/2,0,0]} scale={[8,8,1]}/>
  <Lightformer form="rect" intensity={1} position={[0,2,5]} rotation={[0,Math.PI,0]} scale={[3,3,1]}/>
 </Environment>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,-.005,1.5]}><primitive object={floorGeometry} attach="geometry"/>
 <MeshReflectorMaterial map={floor.map} roughnessMap={floor.roughnessMap} resolution={quality?512:256} blur={[24,12]} mixBlur={1} mixStrength={1.7} mirror={.5} roughness={.3} metalness={0} depthScale={0} color="#e6e6e6"/>
 </mesh>
 {walls.map(w=><GalleryWall key={w.name} wall={w} plaster={plaster}/>)}
 <GalleryCeiling/>

 <directionalLight position={[-3,6,4]} intensity={.75} color="#f8faff" castShadow shadow-mapSize={[quality?2048:1024,quality?2048:1024]} shadow-camera-left={-7} shadow-camera-right={7} shadow-camera-top={7} shadow-camera-bottom={-7} shadow-bias={-.00015} shadow-normalBias={.015}/>
 <directionalLight position={[4,5,-3]} intensity={.3} color="#edf2f9"/>
 {artworks.map((_,i)=><Artwork index={i} key={i}/>)}
 <Box position={[-3.8,.05,3.9]} size={[1.65,.1,.05]} material={new THREE.MeshStandardMaterial({color:'#858781',roughness:.8})}/>
 <Box position={[3.4,.24,3.5]} size={[1.25,.45,.48]} material={new THREE.MeshStandardMaterial({color:'#aa9b80',roughness:.88})}/>
 <Box position={[3.4,.5,3.5]} size={[1.4,.075,.6]} material={new THREE.MeshStandardMaterial({color:'#b7a88e',roughness:.8})}/>
 <WallLettering/>
 <EffectComposer multisampling={quality?4:0}><SMAA/></EffectComposer>
 </>;}
const Space=memo(SpaceScene);
function CameraRig({stateRef,onUpdate}:{stateRef:React.RefObject<State>;onUpdate:(s:State)=>void}){const {camera,gl}=useThree();const stats=useRef({elapsed:0,count:0,frame:0});useEffect(()=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1;stateRef.current.ready=true;onUpdate({...stateRef.current});},[gl,onUpdate,stateRef]);useFrame((_,delta)=>{const s=stateRef.current;const d=Math.min(delta,.1);if(s.playing)s.time=Math.min(duration,s.time+d*s.speed);const view=sampleRoute(s.time);camera.position.fromArray(view.position);camera.lookAt(new THREE.Vector3(...view.target));s.complete=view.complete;s.phase=view.phase;s.artwork=view.artwork;s.collisions=collisionAt(view.position);s.frames++;if(s.frames===4){gl.shadowMap.autoUpdate=false;}stats.current.elapsed+=delta;stats.current.count++;if(stats.current.elapsed>.5){s.fps=Math.round(stats.current.count/stats.current.elapsed);stats.current.count=0;stats.current.elapsed=0;onUpdate({...s});}if(s.complete)s.playing=false;});return null;}
export default function Gallery(){const ref=useRef<State>({...initial});const [state,setState]=useState(initial);const [quality,setQuality]=useState(true);const [diagnostics,setDiagnostics]=useState(false);useEffect(()=>{const query=new URLSearchParams(location.search);ref.current.speed=Number(query.get('speed'))||1;setDiagnostics(query.has('qa'));const onError=(event:ErrorEvent)=>{ref.current.error=event.message;setState({...ref.current});};window.addEventListener('error',onError);return ()=>window.removeEventListener('error',onError);},[]);const mutate=(change:Partial<State>)=>{Object.assign(ref.current,change);setState({...ref.current});};const item=artworks[state.artwork];const focused=state.artwork>=0?exhibitionOrder.indexOf(state.artwork):state.time>=destinations[exhibitionOrder[exhibitionOrder.length-1]]?exhibitionOrder.length:-1;const step=(offset:number)=>{const number=Math.max(0,Math.min(exhibitionOrder.length-1,focused+offset));mutate({time:destinations[exhibitionOrder[number]],artwork:exhibitionOrder[number],phase:"Settle",complete:false,playing:false});};return <main>
 <Canvas shadows dpr={1} camera={{position:[0,1.68,7.4],fov:56,near:.08,far:60}} gl={{antialias:true,powerPreference:'high-performance'}}><Suspense fallback={null}><Space quality={quality}/><CameraRig stateRef={ref} onUpdate={setState}/></Suspense></Canvas>
 <header><a className="brand" href="/" aria-label="VÆST home"><img src="/branding/vaest-logo.png" alt="VÆST"/></a><div className="exhibition">EXHIBITION 001 <span>SPACE BETWEEN</span></div><button className="quality" onClick={()=>setQuality(!quality)}>{quality?'High quality':'Balanced'} <span>↗</span></button></header>
 <div className={`title ${state.time>8?"departed":""}`}><span className="eyebrow">A STUDY IN STILLNESS</span><h1>Space<br/>between.</h1></div>
 <section className="work"><span className="eyebrow">{item?`${String(exhibitionOrder.indexOf(state.artwork)+1).padStart(2,"0")} / ${String(artworks.length).padStart(2,"0")}`:'VÆST / DIGITAL EXHIBITION'}</span><h2>{item?item.title:state.complete?'The way back.':'Enter slowly.'}</h2><p>{item?`${item.medium} · ${item.year}`:'A gallery in light and motion.'}</p></section>
 <footer><div className="transport"><button aria-label={state.playing?'Pause tour':'Resume tour'} onClick={()=>mutate({playing:!state.playing})}>{state.playing?'Ⅱ':'▶'}</button><button aria-label="Restart tour" onClick={()=>mutate({time:0,complete:false,playing:true})}>↺</button><button className="step" aria-label="Previous artwork" disabled={focused<=0} onClick={()=>step(-1)}>Back</button><button className="step" aria-label="Next artwork" disabled={focused>=exhibitionOrder.length-1} onClick={()=>step(1)}>Next</button><span>{state.phase}</span></div><div className="route">{exhibitionOrder.map((i,number)=><button key={artworks[i].title} className={state.artwork===i?'active':''} aria-label={`View ${artworks[i].title}`} onClick={()=>mutate({time:destinations[i],complete:false,playing:true})}>{String(number+1).padStart(2,"0")}</button>)}<div className="progress"><i style={{width:`${state.time/duration*100}%`}}/></div></div></footer>
 {!state.ready&&<div className="loading">VÆST<span>Preparing light and materials</span></div>}
 {diagnostics&&<aside className="diagnostics"><b>Gallery diagnostics</b><p>10 × 10 m main gallery + 10 × 3 m entrance · 4 m high · 2.4 m connecting doorway</p><pre data-testid="diagnostics">{JSON.stringify({...state,quality:quality?'high':'balanced',duration,camera:sampleRoute(state.time).position},null,2)}</pre><label>Tour speed <select aria-label="Tour speed" value={state.speed} onChange={e=>mutate({speed:Number(e.target.value)})}><option value={1}>1 ×</option><option value={4}>4 ×</option><option value={12}>12 ×</option></select></label><small>Placeholder artwork. Architecture inspired by the neutral, top-lit galleries of White Cube Bermondsey; an original 100 m² plan.</small></aside>}
 </main>;}
