'use client';
import {useEffect,useMemo,useRef,useState,Suspense,memo} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Environment,Lightformer,useTexture} from '@react-three/drei';
import {EffectComposer,SMAA} from '@react-three/postprocessing';
import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {wallParts,ceilingBackParts,fins,rooflights} from '../lib/architecture.mjs';
import {RectAreaLightUniformsLib} from 'three/addons/lights/RectAreaLightUniformsLib.js';
RectAreaLightUniformsLib.init();
import {artworks,walls,sampleRoute,duration,destinations,collisionAt} from '../lib/route.mjs';
import {artTexture,artSurface,artLabel,physicalPaintSurface,entrancePrint,exhibitionCopy} from './textures';
const exhibitionOrder=artworks.map((_,i)=>i).sort((a,b)=>destinations[a]-destinations[b]);
type State={time:number;playing:boolean;speed:number;ready:boolean;fps:number;frames:number;complete:boolean;phase:string;artwork:number;collisions:string[];error:string};
const initial:State={time:0,playing:true,speed:1,ready:false,fps:0,frames:0,complete:false,phase:'Arrival',artwork:-1,collisions:[],error:''};
function Box({position,size,material,...rest}:{position:number[];size:number[];material?:THREE.Material;[key:string]:any}){return <mesh position={position as [number,number,number]} material={material} castShadow receiveShadow {...rest}><boxGeometry args={size as [number,number,number]}/>{!material&&<meshStandardMaterial color="#e8e7e1" roughness={.8}/>}</mesh>;}
function contactMap(width:number,height:number){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d')!;const image=ctx.createImageData(512,512);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const px=((x+.5)/512-.5)*(width+.016),py=((y+.5)/512-.5)*(height+.016);const distance=Math.hypot(Math.max(Math.abs(px)-width/2,0),Math.max(Math.abs(py)-height/2,0));const alpha=Math.exp(-distance*distance/(2*.003*.003));const i=(y*512+x)*4;image.data[i]=image.data[i+1]=image.data[i+2]=55;image.data[i+3]=Math.round(alpha*255);}ctx.putImageData(image,0,0);return new THREE.CanvasTexture(c);}
function Artwork({index,suppliedTexture}:{index:number;suppliedTexture?:THREE.Texture}){const a=artworks[index];const texture=useMemo(()=>suppliedTexture||artTexture(index,a.size[0],a.size[1]),[index,a.size,suppliedTexture]);const relief=useMemo(()=>suppliedTexture?physicalPaintSurface(suppliedTexture):artSurface(index),[index,suppliedTexture]);const label=useMemo(()=>artLabel(a.title,a.medium,a.year),[a.title,a.medium,a.year]);const canvasMaterial=useMemo(()=>new THREE.MeshStandardMaterial({map:texture,normalMap:relief.normalMap,roughnessMap:relief.roughnessMap,normalScale:new THREE.Vector2(.22,.22),roughness:.83,metalness:0}),[texture,relief]);const canvasEdge=useMemo(()=>new THREE.MeshStandardMaterial({color:"#d9d2c3",roughness:.95}),[]);const contact=useMemo(()=>contactMap(a.size[0]+.035,a.size[1]+.035),[a.size]);const mountZ=useMemo(()=>{const normal=new THREE.Vector3(0,0,1).applyEuler(new THREE.Euler(...a.rotation as [number,number,number]));const axis=Math.abs(normal.x)>.9?0:2,sign=normal.getComponent(axis)>0?1:-1,tangent=axis===0?2:0;const host=walls.find(w=>{const gap=sign*(a.position[axis]-(sign>0?w.max[axis]:w.min[axis]));return gap>0&&gap<.2&&a.position[tangent]>w.min[tangent]&&a.position[tangent]<w.max[tangent];});return host?-sign*(a.position[axis]-(sign>0?host.max[axis]:host.min[axis]))+.002:-.105;},[a]);return <group position={a.position as [number,number,number]} rotation={a.rotation as [number,number,number]}>
 <mesh position={[0,0,mountZ]}><planeGeometry args={[a.size[0]+.051,a.size[1]+.051]}/><meshBasicMaterial map={contact} transparent opacity={.17} depthWrite={false}/></mesh>
 <Box position={[0,0,(mountZ+.004)/2]} size={[a.size[0]+.035,a.size[1]+.035,-mountZ-.004]} material={new THREE.MeshStandardMaterial({color:"#b6afa0",roughness:.95})}/>
 <mesh position={[0,0,.008]} castShadow material={[canvasEdge,canvasEdge,canvasEdge,canvasEdge,canvasMaterial,canvasEdge]}><boxGeometry args={[a.size[0],a.size[1],.045]}/></mesh>
 <mesh position={[a.size[0]/2+.23,-a.size[1]/2+.1,-.065]}><planeGeometry args={[.24,.105]}/><meshStandardMaterial map={label} color="#ffffff" emissive="#ffffff" emissiveMap={label} emissiveIntensity={.2} roughness={1} envMapIntensity={.03}/></mesh>
 </group>;}
function PhysicalArtwork({index,url}:{index:number;url:string}){const source=useTexture(url);const texture=useMemo(()=>{const map=source.clone();map.colorSpace=THREE.SRGBColorSpace;map.anisotropy=16;const image=source.image as HTMLImageElement,ratio=image.width/image.height,target=artworks[index].size[0]/artworks[index].size[1];map.repeat.set(Math.min(1,target/ratio),Math.min(1,ratio/target));map.offset.set((1-map.repeat.x)/2,(1-map.repeat.y)/2);map.needsUpdate=true;return map;},[source,index]);return <Artwork index={index} suppliedTexture={texture}/>;}
function useLocalSurface(kind:'plaster'|'concrete'){const textures=useTexture([kind==='plaster'?'/textures/provided-white-plaster-v11.avif':'/textures/matte-concrete-v13.avif','/textures/'+kind+'-roughness.jpg','/textures/'+kind+'-normal.jpg']);return useMemo(()=>{const maps=textures.map((t,i)=>{let map=t.clone();if(i===0){const image=t.image as HTMLImageElement;const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d')!;context.drawImage(image,0,0);const data=context.getImageData(0,0,canvas.width,canvas.height);for(let j=0;j<data.data.length;j+=4)for(let c=0;c<3;c++)data.data[j+c]=kind==='plaster'?248+(data.data[j+c]-245)*.16:152+(data.data[j+c]-174)*.52;context.putImageData(data,0,0);map=new THREE.CanvasTexture(canvas);}map.wrapS=map.wrapT=THREE.RepeatWrapping;map.repeat.set(kind==='concrete'?1:4,kind==='concrete'?1:4);map.colorSpace=i===0?THREE.SRGBColorSpace:THREE.NoColorSpace;map.anisotropy=16;map.needsUpdate=true;return map;});const relief=physicalPaintSurface(maps[0]);return {map:maps[0],roughnessMap:kind==='plaster'?relief.roughnessMap:undefined,normalMap:relief.normalMap};},[textures[0],textures[1],textures[2],kind]);}
// Baked surfaces receive complete diffuse transport once; runtime lights retain specular response.
function bakeDiffuseOnly(shader:any){shader.fragmentShader=shader.fragmentShader.replace('#include <lights_fragment_begin>','#include <lights_fragment_begin>\n reflectedLight.directDiffuse=vec3(0.0); irradiance=vec3(0.0);').replace('#include <lights_fragment_end>','iblIrradiance=vec3(0.0);\n#include <lights_fragment_end>');}
function cavityDiffuse(shader:any,kind:'wall'|'ceiling'){bakeDiffuseOnly(shader);shader.vertexShader='varying vec3 vaestWorld;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\nvaestWorld=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader='varying vec3 vaestWorld;\n'+shader.fragmentShader;const visibility=kind==='wall'?'if(vaestWorld.y<0.0251){float h=max(0.025-vaestWorld.y,0.0);cavity=.5+.5*h/sqrt(h*h+.025*.025);cavity*=.8;}':'if(abs(vaestWorld.y-4.075)<.002)cavity=.32;if(abs(inverseTransformDirection(geometryNormal,viewMatrix).y)<.5)cavity*=.72;';
shader.fragmentShader=shader.fragmentShader.replace('#include <lights_fragment_end>',`float cavity=1.0;${visibility}irradiance*=cavity;\n#include <lights_fragment_end>`);}
function useIrradiance(name:string){const source=useTexture('/lightmaps-v13b/'+name+'.png');return useMemo(()=>{const map=source.clone();map.channel=1;map.colorSpace=THREE.SRGBColorSpace;map.minFilter=map.magFilter=THREE.LinearFilter;map.generateMipmaps=false;map.needsUpdate=true;return map;},[source]);}
function wallGeometry(wall:typeof walls[number]){const center=wall.min.map((v,i)=>(v+wall.max[i])/2),span=wall.min.map((v,i)=>wall.max[i]-v);return mergeGeometries(wallParts(wall).map(part=>{const size=part.min.map((v,i)=>part.max[i]-v),g=new RoundedBoxGeometry(...size as [number,number,number],2,.003);g.translate(...part.min.map((v,i)=>(v+part.max[i])/2-center[i]) as [number,number,number]);const uv0=g.getAttribute('uv'),uv=uv0.clone(),p=g.getAttribute('position'),normal=g.getAttribute('normal');for(let j=0;j<p.count;j++){const nx=normal.getX(j),ny=normal.getY(j),nz=normal.getZ(j);const face=Math.abs(nx)>=Math.abs(ny)&&Math.abs(nx)>=Math.abs(nz)?(nx>0?0:1):Math.abs(ny)>=Math.abs(nz)?(ny>0?2:3):(nz>0?4:5);const x=p.getX(j)+center[0],y=p.getY(j)+center[1],z=p.getZ(j)+center[2];let u=0,v=0;if(face<2){u=face===0?(wall.max[2]-z)/span[2]:(z-wall.min[2])/span[2];v=(y-wall.min[1])/span[1];}else if(face<4){u=(x-wall.min[0])/span[0];v=face===2?(wall.max[2]-z)/span[2]:(z-wall.min[2])/span[2];}else{u=face===4?(x-wall.min[0])/span[0]:(wall.max[0]-x)/span[0];v=(y-wall.min[1])/span[1];}uv.setXY(j,(u*47+.5+face*48)/288,(v*47+.5)/48);uv0.setXY(j,u*(face<2?span[2]:span[0]),v*(face===2||face===3?span[2]:span[1]));}g.setAttribute('uv1',uv);return g;}))!;}
function GalleryWall({wall,plaster}:{wall:typeof walls[number];plaster:THREE.MeshStandardMaterial}){const lightMap=useIrradiance(wall.name);const geometry=useMemo(()=>wallGeometry(wall),[wall]);const material=useMemo(()=>{const m=plaster.clone();m.emissiveIntensity=0;m.lightMap=lightMap;m.lightMapIntensity=19.2*Math.PI;m.onBeforeCompile=shader=>cavityDiffuse(shader,'wall');m.customProgramCacheKey=()=> 'vaest-wall-cavity-v13';return m;},[plaster,lightMap]);return <mesh position={wall.min.map((v,i)=>(v+wall.max[i])/2) as [number,number,number]} geometry={geometry} material={material}/>;}
function worldUVGeometry(parts:{min:number[];max:number[]}[]){return mergeGeometries(parts.map(part=>{const g=new THREE.BoxGeometry(...part.min.map((v,i)=>part.max[i]-v) as [number,number,number]);g.translate(...part.min.map((v,i)=>(v+part.max[i])/2) as [number,number,number]);const p=g.getAttribute('position'),uv=g.getAttribute('uv').clone();for(let i=0;i<p.count;i++)uv.setXY(i,(p.getX(i)+14.2)/28.4,1-(p.getZ(i)+5.2)/14.4);g.setAttribute('uv1',uv);return g;}))!;}
function finGeometry(){return mergeGeometries(fins.map(fin=>{const shape=new THREE.Shape();shape.moveTo(-fin.width/2,0);shape.lineTo(fin.width/2,fin.rise);shape.lineTo(fin.width/2,.2);shape.lineTo(-fin.width/2,.2);shape.closePath();const g=new THREE.ExtrudeGeometry(shape,{depth:fin.max[2]-fin.min[2],bevelEnabled:true,bevelThickness:.002,bevelSize:.002,bevelSegments:2,steps:1});g.translate(fin.x,4,fin.min[2]);const p=g.getAttribute('position'),uv=g.getAttribute('uv').clone();for(let i=0;i<p.count;i++)uv.setXY(i,(p.getX(i)+14.2)/28.4,1-(p.getZ(i)+5.2)/14.4);g.setAttribute('uv1',uv);return g;}))!;}
function entranceGrid(){const pieces:THREE.BufferGeometry[]=[];for(let x=-13.98;x<=13.98;x+=.12){const g=new THREE.BoxGeometry(.014,.018,3.68);g.translate(x,3.998,7.08);pieces.push(g);}for(let z=5.24;z<=8.92;z+=.12){const g=new THREE.BoxGeometry(27.96,.018,.014);g.translate(0,3.998,z);pieces.push(g);}return mergeGeometries(pieces)!;}
function GalleryCeiling(){const ceilingIrradiance=useIrradiance('ceiling');const white=useMemo(()=>{const m=new THREE.MeshStandardMaterial({color:'#ffffff',roughness:.95,lightMap:ceilingIrradiance,lightMapIntensity:20.8*Math.PI,envMapIntensity:.12});m.onBeforeCompile=shader=>{cavityDiffuse(shader,'ceiling');shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\n if(vaestWorld.z>4.98) diffuseColor.rgb*=.035;');};m.customProgramCacheKey=()=> 'vaest-ceiling-fins-v13';return m;},[ceilingIrradiance]);const geometry=useMemo(finGeometry,[]),back=useMemo(()=>worldUVGeometry(ceilingBackParts),[]),grid=useMemo(entranceGrid,[]);return <><mesh geometry={grid}><meshStandardMaterial color="#242526" roughness={.88} envMapIntensity={.15}/></mesh><mesh geometry={geometry} material={white}/><mesh geometry={back} material={white}/>{rooflights.map(({x,z,width,depth,height})=><mesh key={x+','+z} rotation={[Math.PI/2,0,0]} position={[x,height,z]}><planeGeometry args={[width,depth]}/><meshStandardMaterial color="#fff" emissive="#ffffff" emissiveIntensity={3} roughness={1}/></mesh>)}{[-3,0,3].map(x=><rectAreaLight key={'gallery'+x} position={[x,3.98,0]} rotation={[-Math.PI/2,0,0]} width={2.5} height={9} intensity={.9} color="#ffffff"/>)}{[-10,0,10].map(x=><rectAreaLight key={'entrance'+x} position={[x,3.98,7]} rotation={[-Math.PI/2,0,0]} width={7} height={3.5} intensity={.9} color="#ffffff"/>)}</>;}
function EntranceText(){const left=useMemo(()=>entrancePrint('exhibition'),[]),right=useMemo(()=>entrancePrint('biography'),[]);return <>{[[-2.07,left],[2.07,right]].map(([x,map],index)=><mesh key={index} position={[x as number,2.1,5.181]}><planeGeometry args={[1.55,1.55*1400/2048]}/><meshBasicMaterial map={map as THREE.Texture} transparent depthWrite={false} toneMapped={false}/></mesh>)}</>;}
function floorShape(){const shape=new THREE.Shape();const points=[[-5.2,-5.2],[5.2,-5.2],[5.2,4.98],[14.2,4.98],[14.2,9.2],[-14.2,9.2],[-14.2,4.98],[-5.2,4.98]];points.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();const g=new THREE.ShapeGeometry(shape),p=g.getAttribute('position'),uv=g.getAttribute('uv');for(let i=0;i<p.count;i++)uv.setXY(i,(p.getX(i)+14.2)/28.4,(p.getY(i)+9.2)/14.4);g.setAttribute('uv1',uv.clone());return g;}
function SpaceScene(){const plasterMaps=useLocalSurface('plaster');const plaster=useMemo(()=>new THREE.MeshStandardMaterial({...plasterMaps,color:'#ffffff',roughness:.9,normalScale:new THREE.Vector2(.045,.045),emissive:'#ffffff',emissiveIntensity:.16}),[plasterMaps]);const floor=useLocalSurface('concrete');const floorIrradiance=useIrradiance('floor');const floorGeometry=useMemo(floorShape,[]);return <>
 <color attach="background" args={['#d6d4cc']}/><fog attach="fog" args={['#e4e3dc',15,38]}/>
 <hemisphereLight args={['#ffffff','#e8e9e6',.4]}/><ambientLight intensity={.1}/>
 <Environment resolution={256} frames={1}>
  <Lightformer form="rect" intensity={1.4} color="#ffffff" position={[0,3.9,0]} rotation={[Math.PI/2,0,0]} scale={[8,8,1]}/>
  <Lightformer form="rect" intensity={1} position={[0,2,5]} rotation={[0,Math.PI,0]} scale={[3,3,1]}/>
 </Environment>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,-.005,0]}><primitive object={floorGeometry} attach="geometry"/>
 <meshStandardMaterial map={floor.map} normalMap={floor.normalMap} normalScale={new THREE.Vector2(.015,.015)} lightMap={floorIrradiance} lightMapIntensity={17.6*Math.PI} roughness={.98} metalness={0} envMapIntensity={.015} color="#ffffff" onBeforeCompile={bakeDiffuseOnly}/>

 </mesh>
 {walls.map(w=><GalleryWall key={w.name} wall={w} plaster={plaster}/>)}
 <GalleryCeiling/>

 <directionalLight position={[-3,6,4]} intensity={.6} color="#f8faff" castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-7} shadow-camera-right={7} shadow-camera-top={7} shadow-camera-bottom={-7} shadow-bias={-.00015} shadow-normalBias={.015}/>
 <directionalLight position={[4,5,-3]} intensity={.3} color="#edf2f9"/>
 {artworks.map((_,i)=>i===1?<PhysicalArtwork key={i} index={i} url="/artworks/after-rain-study-v1-web.jpg"/>:i===0?<PhysicalArtwork key={i} index={i} url="/artworks/sediment-study-v1-publish.jpg"/>:<Artwork index={i} key={i}/>)}
 <EntranceText/>
 <EffectComposer multisampling={4}><SMAA/></EffectComposer>
 </>;}
const Space=memo(SpaceScene);
function CameraRig({stateRef,onUpdate,introActive}:{stateRef:React.RefObject<State>;onUpdate:(s:State)=>void;introActive:boolean}){const {camera,gl}=useThree();const stats=useRef({elapsed:0,count:0,frame:0});useEffect(()=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1;stateRef.current.ready=true;onUpdate({...stateRef.current});},[gl,onUpdate,stateRef]);useFrame((_,delta)=>{const s=stateRef.current;const d=Math.min(delta,.1);if(s.playing&&!introActive)s.time=Math.min(duration,s.time+d*s.speed);const view=sampleRoute(s.time);camera.position.fromArray(view.position);camera.lookAt(new THREE.Vector3(...view.target));s.complete=view.complete;s.phase=view.phase;s.artwork=view.artwork;s.collisions=collisionAt(view.position);s.frames++;if(s.frames===4){gl.shadowMap.autoUpdate=false;}stats.current.elapsed+=delta;stats.current.count++;if(stats.current.elapsed>.5){s.fps=Math.round(stats.current.count/stats.current.elapsed);stats.current.count=0;stats.current.elapsed=0;onUpdate({...s});}if(s.complete)s.playing=false;});return null;}
export default function Gallery({introActive=false}:{introActive?:boolean}={}){const ref=useRef<State>({...initial});const [state,setState]=useState(initial);const [diagnostics,setDiagnostics]=useState(false);useEffect(()=>{const query=new URLSearchParams(location.search);ref.current.speed=Number(query.get('speed'))||1;setDiagnostics(query.has('qa'));const onError=(event:ErrorEvent)=>{ref.current.error=event.message;setState({...ref.current});};window.addEventListener('error',onError);return ()=>window.removeEventListener('error',onError);},[]);const mutate=(change:Partial<State>)=>{Object.assign(ref.current,change);setState({...ref.current});};const item=artworks[state.artwork];const scrub=(time:number)=>{const view=sampleRoute(time);mutate({time,playing:false,complete:view.complete,phase:view.phase,artwork:view.artwork});};return <main>
 <Canvas shadows dpr={1.25} camera={{position:[0,1.68,8.2],fov:56,near:.08,far:80}} gl={{antialias:true,powerPreference:'high-performance'}}><Suspense fallback={null}><Space/><CameraRig stateRef={ref} onUpdate={setState} introActive={introActive}/></Suspense></Canvas>
 <header><a className="brand" href="/" aria-label="VÆST home"><img src="/branding/vaest-logo.png" alt="VÆST"/></a><div className="exhibition artist-heading">WESTHOFF</div><div className="header-controls"><a className="bio-link" href="/bio">Bio</a><a className="instagram" href="https://www.instagram.com/vaest.art/" target="_blank" rel="noopener noreferrer" aria-label="VÆST on Instagram"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="12" r="10.5" stroke="currentColor" strokeWidth="1.1"/><rect x="6.8" y="6.8" width="10.4" height="10.4" rx="3" stroke="currentColor" strokeWidth="1.2"/><circle cx="12" cy="12" r="2.65" stroke="currentColor" strokeWidth="1.2"/><circle cx="15.4" cy="8.8" r=".75" fill="currentColor"/></svg></a></div></header>
 <section className="work"><span className="eyebrow">{item?`${String(exhibitionOrder.indexOf(state.artwork)+1).padStart(2,"0")} / ${String(artworks.length).padStart(2,"0")}`:'VÆST / DIGITAL EXHIBITION'}</span><h2>{item?item.title:state.complete?'The way back.':'Enter slowly.'}</h2><p>{item?`${item.medium} · ${item.year}`:'A gallery in light and motion.'}</p></section>
 <footer><div className="transport"><button aria-label={state.playing?'Pause tour':'Resume tour'} onClick={()=>state.complete?mutate({time:0,playing:true,complete:false,artwork:sampleRoute(0).artwork,phase:sampleRoute(0).phase}):mutate({playing:!state.playing})}>{state.playing?'Ⅱ':'▶'}</button><button aria-label="Restart tour" onClick={()=>mutate({time:0,complete:false,playing:true})}>↺</button><input className="timeline" aria-label="Exhibition timeline" type="range" min={0} max={duration} step={.1} value={state.time} onChange={e=>scrub(Number(e.target.value))}/><button className="speed-token" aria-label="Playback speed x1" aria-pressed={state.speed===1} onClick={()=>mutate({speed:1})}>x1</button><button className="speed-token" aria-label="Playback speed x2" aria-pressed={state.speed===2} onClick={()=>mutate({speed:2})}>x2</button></div><div className="route">{exhibitionOrder.map((i,number)=><button key={artworks[i].title} className={state.artwork===i?'active':''} aria-label={`View ${artworks[i].title}`} onClick={()=>scrub(destinations[i])}>{String(number+1).padStart(2,"0")}</button>)}</div></footer>
 {!state.ready&&<div className="quiet-loading" aria-label="VÆST loading"><div className="brand"><img src="/branding/vaest-logo.png" alt="VÆST"/></div></div>}
 {diagnostics&&<aside className="diagnostics"><b>Gallery diagnostics</b><p>10 × 10 m main gallery + 28 × 4 m entrance · Outer walls 4 m · Dividers 3 m · Doorways 2.4 × 4 m</p><pre data-testid="diagnostics">{JSON.stringify({...state,introActive,quality:'high',duration,camera:sampleRoute(state.time).position},null,2)}</pre><label>Tour speed <select aria-label="Tour speed" value={state.speed} onChange={e=>mutate({speed:Number(e.target.value)})}><option value={1}>1 ×</option><option value={2}>2 ×</option><option value={3}>3 ×</option><option value={4}>4 ×</option><option value={12}>12 ×</option></select></label><small>Placeholder artwork. Architecture inspired by the neutral, top-lit galleries of White Cube Bermondsey; an original 100 m² main gallery plus 112 m² entrance.</small></aside>}
 </main>;}
