export const floorBounds:{min:number[];max:number[]};
export const rooflights:{x:number;z:number;width:number;depth:number;height:number;radiance:number}[];
export const fins:{x:number;z:number;axis:number;width:number;rise:number;min:number[];max:number[]}[];
export const ceilingBackParts:{min:number[];max:number[]}[];
export const ceilingParts:{min:number[];max:number[]}[];
export function ceilingLevel(x:number,z:number):number|null;
export function backLevel(x:number,z:number):number|null;
export function inFootprint(x:number,z:number):boolean;
export function wallParts(w:{min:number[];max:number[]}):{min:number[];max:number[]}[];
