import {PerspectiveCamera,Vector3,Euler} from 'three';
import {artworks,sampleRoute,destinations,viewingWindows,walls,closingView} from '../lib/route.mjs';
const holds=viewingWindows.map(window=>window[1]);
const results=[];
for(const [width,height] of [[1280,720],[805,724]])for(let i=0;i<artworks.length;i++){
 const camera=new PerspectiveCamera(56,width/height,.08,80),a=artworks[i];let maximum=0,verticalError=0,eyeError=0;
 for(let t=destinations[i];t<=holds[i]+.0001;t+=.1){const s=sampleRoute(t);eyeError=Math.max(eyeError,Math.abs(s.position[1]-a.position[1]),Math.abs(s.target[1]-a.position[1]));camera.position.fromArray(s.position);camera.lookAt(new Vector3(...s.target));camera.updateMatrixWorld();
 for(const x of [-a.size[0]/2,a.size[0]/2]){const top=new Vector3(x,a.size[1]/2,0).applyEuler(new Euler(...a.rotation)).add(new Vector3(...a.position)).project(camera);const bottom=new Vector3(x,-a.size[1]/2,0).applyEuler(new Euler(...a.rotation)).add(new Vector3(...a.position)).project(camera);verticalError=Math.max(verticalError,Math.abs(top.x-bottom.x));}for(const x of [-a.size[0]/2,a.size[0]/2])for(const y of [-a.size[1]/2,a.size[1]/2]){const p=new Vector3(x,y,0).applyEuler(new Euler(...a.rotation)).add(new Vector3(...a.position)).project(camera);maximum=Math.max(maximum,Math.abs(p.x),Math.abs(p.y));}}
 const settled=sampleRoute(destinations[i]),normal=new Vector3(0,0,1).applyEuler(new Euler(...a.rotation)),outward=new Vector3(...settled.position).sub(new Vector3(...a.position)),distance=outward.length(),frontalError=normal.distanceTo(outward.normalize());results.push({viewport:[width,height],artwork:i+1,maximumNDC:Number(maximum.toFixed(3)),distance:Number(distance.toFixed(3)),frontalError,eyeError,verticalError,pass:maximum<.94&&frontalError<1e-6&&eyeError<1e-6&&verticalError<1e-6});
}
const mounting=artworks.map((a,index)=>{const rotation=new Euler(...a.rotation),normal=new Vector3(0,0,1).applyEuler(rotation),axis=Math.abs(normal.x)>.9?0:2,tangent=axis===0?2:0,sign=normal.getComponent(axis)>0?1:-1;const host=walls.find(w=>Math.abs(a.position[axis]-(sign>0?w.max[axis]:w.min[axis]))<.15&&a.position[tangent]-(a.size[0]+.035)/2>=w.min[tangent]&&a.position[tangent]+(a.size[0]+.035)/2<=w.max[tangent]&&a.position[1]-(a.size[1]+.035)/2>=w.min[1]&&a.position[1]+(a.size[1]+.035)/2<=w.max[1]);return {artwork:index+1,host:host?.name,pass:!!host};});
const closingCamera=new PerspectiveCamera(56,1280/720,.08,80),closingResults=[];
for(let t=closingView.align;t<=closingView.end+4+.0001;t+=.05){const s=sampleRoute(t);closingCamera.position.fromArray(s.position);closingCamera.lookAt(new Vector3(...s.target));closingCamera.updateMatrixWorld();let max=0;const art=artworks[3];for(const x of [-art.size[0]/2,art.size[0]/2])for(const y of [-art.size[1]/2,art.size[1]/2]){const point=new Vector3(x,y,0).add(new Vector3(...art.position)).project(closingCamera);max=Math.max(max,Math.abs(point.x),Math.abs(point.y));}closingResults.push({time:t,pass:Math.abs(s.position[0])<1e-8&&Math.abs(s.position[1]-art.position[1])<1e-8&&s.target.every((v,i)=>Math.abs(v-art.position[i])<1e-8)&&max<.94});}
const pass=closingResults.every(r=>r.pass)&&results.every(r=>r.pass)&&mounting.every(r=>r.pass);console.log(JSON.stringify({pass,results,mounting,closing:{...closingView,samples:closingResults.length,pass:closingResults.every(r=>r.pass)}},null,2));if(!pass)process.exitCode=1;
